apiVersion: v1
kind: Service
metadata:
  name: reg-atlas
  namespace: reg-atlas
spec:
  selector:
    app: reg-atlas
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
