apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "reg-atlas.labels" . | nindent 4 }}
data:
  REG_ATLAS_NO_LLM: {{ .Values.env.REG_ATLAS_NO_LLM | quote }}
  DATA_DIR: {{ .Values.env.DATA_DIR | quote }}
  CHROMA_PERSIST_DIR: {{ .Values.env.CHROMA_PERSIST_DIR | quote }}
